### ISSUE TITLE
We have to add feature through which we can Search Room.

### ISSUE THREAD

**Issue by vikas159** [vikas159/HMS#3]

**Comment by Shubham-Gupta3197** [comment]
@vikas159 let me try to help you. Please assign all 3 issues to me. It will take some time but I'm sure I'll help you.

**Comment by vikas159** [comment]
Hey @Shubham-Gupta3197 i have assigned you the other issues also. but i have less time need your help nro.

**Comment by Shubham-Gupta3197** [comment]
@vikas159 hi vikas, I'm working on your issues only, just give me one more day.
